---
  config:
    irc_channels: 
      - "#mqttbot"
      - "#mqttbot2"
    irc_nickname: "mqttbot"
    irc_server: "irc.libera.chat"
    irc_port: 6667

    mqtt_host: "mqtthost.example.com"
    mqtt_port: 1883
    mqtt_client_id: "irctomqttbot"
    mqtt_username:
    mqtt_password:

  commands:
    # Works on all channels because no channel is defined
    lights on:
      topic: "irc/light"
      message: "on"

    lights off:
      topic: "irc/light"
      message: "off"

    # Only usable in defined channels
    unlock door:
      topic: "irc/door"
      message: "off"
      channels:
        - "#mqttbot2"
